### ISSUE TITLE
Invalid homepage

### ISSUE THREAD

**Issue by jkovalsky** [hectorespert/nb-native-notifications#9]
Can you please fix the homepage URL in both plugin descriptions? Right now it shows [https://github.com/blackleg/nb-native-notifications/quote](https://github.com/blackleg/nb-native-notifications/quote) Then please reupload to Maven central and NetBeans Plugin Portal.

**Comment by hectorespert** [comment]
@jkovalsky How can I check if it was fixed? I can't see these urls in both sites.

**Comment by jkovalsky** [comment]
Well, I think that 1.2.3 version of your [https://plugins.netbeans.apache.org/catalogue/?id=42](https://plugins.netbeans.apache.org/catalogue/?id=42) plugin already contains correct [https://github.com/blackleg/nb-native-notifications](https://github.com/blackleg/nb-native-notifications) URL. Thanks!
